// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LaplacianSmoothing
Rcpp::List LaplacianSmoothing(Eigen::MatrixXd coefficients, const Rcpp::IntegerVector& indices, const Rcpp::IntegerVector& adjacencies, const Rcpp::IntegerVector& pointers, const double tol, const int max_iter);
RcppExport SEXP _midr_LaplacianSmoothing(SEXP coefficientsSEXP, SEXP indicesSEXP, SEXP adjacenciesSEXP, SEXP pointersSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type adjacencies(adjacenciesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pointers(pointersSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(LaplacianSmoothing(coefficients, indices, adjacencies, pointers, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// fastLmMatrix
Rcpp::List fastLmMatrix(Rcpp::NumericMatrix X, Rcpp::NumericMatrix y, int method);
RcppExport SEXP _midr_fastLmMatrix(SEXP XSEXP, SEXP ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrix(X, y, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_midr_LaplacianSmoothing", (DL_FUNC) &_midr_LaplacianSmoothing, 6},
    {"_midr_fastLmMatrix", (DL_FUNC) &_midr_fastLmMatrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_midr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
