// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LaplacianSmoothing
Rcpp::List LaplacianSmoothing(Rcpp::NumericMatrix coefficients, const Rcpp::IntegerVector& targets, const Rcpp::IntegerVector& adjacencies, const Rcpp::IntegerVector& pointers, const double tol, const int max_iter);
RcppExport SEXP _midr_LaplacianSmoothing(SEXP coefficientsSEXP, SEXP targetsSEXP, SEXP adjacenciesSEXP, SEXP pointersSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type adjacencies(adjacenciesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pointers(pointersSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(LaplacianSmoothing(coefficients, targets, adjacencies, pointers, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_midr_LaplacianSmoothing", (DL_FUNC) &_midr_LaplacianSmoothing, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_midr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
