# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LaplacianSmoothing <- function(coefficients, indices, adjacencies, pointers, tol, max_iter) {
    .Call(`_midr_LaplacianSmoothing`, coefficients, indices, adjacencies, pointers, tol, max_iter)
}

fastLmMatrix <- function(X, y, method = 0L) {
    .Call(`_midr_fastLmMatrix`, X, y, method)
}

