# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LaplacianSmoothing <- function(coefficients, targets, adjacencies, pointers, tol = 0.0000001, max_iter = 10000L) {
    .Call(`_midr_LaplacianSmoothing`, coefficients, targets, adjacencies, pointers, tol, max_iter)
}

